// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_WelcomeScreen
void ui_WelcomeScreen_screen_init(void);
lv_obj_t * ui_WelcomeScreen;
lv_obj_t * ui_Label10;
void ui_event_freeStyle(lv_event_t * e);
lv_obj_t * ui_freeStyle;
lv_obj_t * ui_Label2;
void ui_event_DemoMode(lv_event_t * e);
lv_obj_t * ui_DemoMode;
lv_obj_t * ui_Label3;


// SCREEN: ui_DemoScreen
void ui_DemoScreen_screen_init(void);
lv_obj_t * ui_DemoScreen;
void ui_event_Button3(lv_event_t * e);
lv_obj_t * ui_Button3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Container1;
void ui_event_targetTslider(lv_event_t * e);
lv_obj_t * ui_targetTslider;
lv_obj_t * ui_Label7;
lv_obj_t * ui_targetV;
lv_obj_t * ui_Label9;
void ui_event_startstop(lv_event_t * e);
lv_obj_t * ui_startstop;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Label17;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Label14;
lv_obj_t * ui_Label15;
lv_obj_t * ui_Label16;
lv_obj_t * ui_demoState;
lv_obj_t * ui_vibration;
lv_obj_t * ui_heatingState;
lv_obj_t * ui_coolingState;
lv_obj_t * ui_temperature;


// SCREEN: ui_FreeStyleScreen
void ui_FreeStyleScreen_screen_init(void);
lv_obj_t * ui_FreeStyleScreen;
void ui_event_Button1(lv_event_t * e);
lv_obj_t * ui_Button1;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Label18;
lv_obj_t * ui_Label20;
void ui_event_heatingState2(lv_event_t * e);
lv_obj_t * ui_heatingState2;
lv_obj_t * ui_temperature2;
void ui_event_currentSetV(lv_event_t * e);
lv_obj_t * ui_currentSetV;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_freeStyle(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_FreeStyleScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_FreeStyleScreen_screen_init);
        _ui_screen_delete(&ui_WelcomeScreen);
    }
}
void ui_event_DemoMode(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DemoScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_DemoScreen_screen_init);
        _ui_screen_delete(&ui_WelcomeScreen);
    }
}
void ui_event_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_DemoScreen);
        _ui_screen_change(&ui_WelcomeScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_WelcomeScreen_screen_init);
    }
}
void ui_event_targetTslider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label17, target, "", "");
    }
}
void ui_event_startstop(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        startStopButtonClicked(e);
    }
}
void ui_event_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_delete(&ui_FreeStyleScreen);
        _ui_screen_change(&ui_WelcomeScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_WelcomeScreen_screen_init);
    }
}
void ui_event_heatingState2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        turnOnHeatingElement(e);
    }
}
void ui_event_currentSetV(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_VALUE_CHANGED) {
        setVibrationLevel(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    LV_EVENT_GET_COMP_CHILD = lv_event_register_id();

    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_WelcomeScreen_screen_init();
    ui_DemoScreen_screen_init();
    ui_FreeStyleScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_WelcomeScreen);
}
