// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_WelcomeScreen
void ui_WelcomeScreen_screen_init(void);
extern lv_obj_t * ui_WelcomeScreen;
extern lv_obj_t * ui_Label10;
void ui_event_freeStyle(lv_event_t * e);
extern lv_obj_t * ui_freeStyle;
extern lv_obj_t * ui_Label2;
void ui_event_DemoMode(lv_event_t * e);
extern lv_obj_t * ui_DemoMode;
extern lv_obj_t * ui_Label3;
// SCREEN: ui_DemoScreen
void ui_DemoScreen_screen_init(void);
extern lv_obj_t * ui_DemoScreen;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container1;
void ui_event_targetTslider(lv_event_t * e);
extern lv_obj_t * ui_targetTslider;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_targetV;
extern lv_obj_t * ui_Label9;
void ui_event_startstop(lv_event_t * e);
extern lv_obj_t * ui_startstop;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_demoState;
extern lv_obj_t * ui_vibration;
extern lv_obj_t * ui_heatingState;
extern lv_obj_t * ui_coolingState;
extern lv_obj_t * ui_temperature;
// SCREEN: ui_FreeStyleScreen
void ui_FreeStyleScreen_screen_init(void);
extern lv_obj_t * ui_FreeStyleScreen;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label20;
void ui_event_heatingState2(lv_event_t * e);
extern lv_obj_t * ui_heatingState2;
extern lv_obj_t * ui_temperature2;
void ui_event_currentSetV(lv_event_t * e);
extern lv_obj_t * ui_currentSetV;
extern lv_obj_t * ui____initial_actions0;








void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
