// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"

// SCREEN: ui_WelcomeScreen
void ui_WelcomeScreen_screen_init(void);
extern lv_obj_t * ui_WelcomeScreen;
extern lv_obj_t * ui_Label10;
void ui_event_DemoMode(lv_event_t * e);
extern lv_obj_t * ui_DemoMode;
extern lv_obj_t * ui_Label3;
void ui_event_ImgButton4(lv_event_t * e);
extern lv_obj_t * ui_ImgButton4;
extern lv_obj_t * ui_Image2;
// SCREEN: ui_DemoScreen
void ui_DemoScreen_screen_init(void);
extern lv_obj_t * ui_DemoScreen;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container1;
void ui_event_targetTslider(lv_event_t * e);
extern lv_obj_t * ui_targetTslider;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_targetV;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Label17;
void ui_event_startstop(lv_event_t * e);
extern lv_obj_t * ui_startstop;
extern lv_obj_t * ui_LabelStart;
extern lv_obj_t * ui_LabelStop;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_demoState;
extern lv_obj_t * ui_vibration;
extern lv_obj_t * ui_heatingState;
extern lv_obj_t * ui_coolingState;
extern lv_obj_t * ui_temperature;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label9;
void ui_event_enableTDemo(lv_event_t * e);
extern lv_obj_t * ui_enableTDemo;
// SCREEN: ui_FreeStyleScreen
void ui_FreeStyleScreen_screen_init(void);
extern lv_obj_t * ui_FreeStyleScreen;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_demoState2;
extern lv_obj_t * ui_vibration2;
extern lv_obj_t * ui_heatingState3;
extern lv_obj_t * ui_coolingState3;
extern lv_obj_t * ui_temperature2;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_Vlevels;
void ui_event_saveVLevels(lv_event_t * e);
extern lv_obj_t * ui_saveVLevels;
extern lv_obj_t * ui_Label26;
void ui_event_loadVLevels(lv_event_t * e);
extern lv_obj_t * ui_loadVLevels;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label22;
void ui_event_viblow(lv_event_t * e);
extern lv_obj_t * ui_viblow;
void ui_event_vibmid(lv_event_t * e);
extern lv_obj_t * ui_vibmid;
void ui_event_vibhigh(lv_event_t * e);
extern lv_obj_t * ui_vibhigh;
void ui_event_vibmax(lv_event_t * e);
extern lv_obj_t * ui_vibmax;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Lblviblow;
extern lv_obj_t * ui_Lblvibmid;
extern lv_obj_t * ui_Lblvibhigh;
extern lv_obj_t * ui_Lblvibmax;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_hintv;
extern lv_obj_t * ui_Flevel;
extern lv_obj_t * ui_Container5;
void ui_event_vibmax1(lv_event_t * e);
extern lv_obj_t * ui_vibmax1;
extern lv_obj_t * ui_Lblvibmax1;
void ui_event_saveFanLevel(lv_event_t * e);
extern lv_obj_t * ui_saveFanLevel;
extern lv_obj_t * ui_Label33;
void ui_event_loadFanLevel(lv_event_t * e);
extern lv_obj_t * ui_loadFanLevel;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label34;
extern lv_obj_t * ui_hintfan;
extern lv_obj_t * ui_Test;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Label20;
void ui_event_heatingSwitch(lv_event_t * e);
extern lv_obj_t * ui_heatingSwitch;
void ui_event_coolingSwitch(lv_event_t * e);
extern lv_obj_t * ui_coolingSwitch;
void ui_event_currentSetV(lv_event_t * e);
extern lv_obj_t * ui_currentSetV;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_hinttest;
void ui_event_reset(lv_event_t * e);
extern lv_obj_t * ui_reset;
extern lv_obj_t * ui_Label35;
extern lv_obj_t * ui____initial_actions0;


LV_IMG_DECLARE(ui_img_setting2_png);    // assets/setting2.png
LV_IMG_DECLARE(ui_img_1984690215);    // assets/th_sew-eurodrive.png






void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
