// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_COMP_PANEL1_H
#define _UI_COMP_PANEL1_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Panel1
#define UI_COMP_PANEL1_PANEL1 0
#define UI_COMP_PANEL1_LABEL12 1
#define _UI_COMP_PANEL1_NUM 2
lv_obj_t * ui_Panel1_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
