// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void startStopButtonClicked(lv_event_t * e);
void saveV_Levels(lv_event_t * e);
void loadV_Levels(lv_event_t * e);
void saveFanMaxLevel(lv_event_t * e);
void loadFanMaxLevel(lv_event_t * e);
void turnOnOffHeatingElement(lv_event_t * e);
void turnOnOffCoolingFan(lv_event_t * e);
void setVibrationLevel(lv_event_t * e);
void reset_btn_clicked(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
