// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"

void ui_WelcomeScreen_screen_init(void)
{
    ui_WelcomeScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_WelcomeScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WelcomeScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WelcomeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_WelcomeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_WelcomeScreen, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WelcomeScreen, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_WelcomeScreen, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WelcomeScreen, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_WelcomeScreen);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -2);
    lv_obj_set_y(ui_Label10, -88);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Welcome to Temperature & Vibration \n                   Monitoring Demo");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xD00101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_40, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DemoMode = lv_btn_create(ui_WelcomeScreen);
    lv_obj_set_width(ui_DemoMode, 392);
    lv_obj_set_height(ui_DemoMode, 100);
    lv_obj_set_x(ui_DemoMode, -11);
    lv_obj_set_y(ui_DemoMode, 60);
    lv_obj_set_align(ui_DemoMode, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DemoMode, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DemoMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DemoMode, 30, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_DemoMode, lv_color_hex(0xD00101), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_DemoMode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_DemoMode, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_DemoMode, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_DemoMode);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Click Here to Start");
    lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ImgButton4 = lv_imgbtn_create(ui_WelcomeScreen);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_setting2_png, NULL);
    lv_imgbtn_set_src(ui_ImgButton4, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_setting2_png, NULL);
    lv_obj_set_width(ui_ImgButton4, 67);
    lv_obj_set_height(ui_ImgButton4, 67);
    lv_obj_set_x(ui_ImgButton4, 364);
    lv_obj_set_y(ui_ImgButton4, -205);
    lv_obj_set_align(ui_ImgButton4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ImgButton4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ImgButton4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Image2 = lv_img_create(ui_WelcomeScreen);
    lv_img_set_src(ui_Image2, &ui_img_1984690215);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 250
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 167
    lv_obj_set_x(ui_Image2, -333);
    lv_obj_set_y(ui_Image2, 199);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 128);

    lv_obj_add_event_cb(ui_DemoMode, ui_event_DemoMode, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ImgButton4, ui_event_ImgButton4, LV_EVENT_ALL, NULL);

}
